package com.gymflow.ui;

/** Identifies the application screens. */
public enum Screen {
    LOGIN,
    OWNER_HOME,
    OWNER_MEMBERS,
    OWNER_MEMBERSHIPS,
    OWNER_FINANCES,
    OWNER_VISITS,
    OWNER_ANNOUNCEMENTS,
    OWNER_ACCOUNTS,
    MEMBER_HOME,
    MEMBER_MEMBERSHIP,
    MEMBER_WORKOUTS,
    MEMBER_BODY_METRICS,
    MEMBER_ANNOUNCEMENTS,
    MEMBER_PROFILE
}
