CREATE TABLE public.visits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id bigint NOT NULL
        REFERENCES public.member_profiles(account_id) ON DELETE CASCADE,
    entered_at timestamp with time zone NOT NULL,
    exited_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    corrected_at timestamp with time zone,
    corrected_by_account_id bigint REFERENCES public.accounts(id),
    correction_reason text,
    CHECK (exited_at IS NULL OR exited_at > entered_at),
    CHECK (
        (
            corrected_at IS NULL
            AND corrected_by_account_id IS NULL
            AND correction_reason IS NULL
        )
        OR (
            corrected_at IS NOT NULL
            AND corrected_by_account_id IS NOT NULL
            AND length(trim(correction_reason)) > 0
        )
    )
);

CREATE UNIQUE INDEX visits_one_open_per_member
    ON public.visits (member_account_id)
    WHERE exited_at IS NULL;

CREATE INDEX visits_member_entered_at_idx
    ON public.visits (member_account_id, entered_at DESC);

ALTER TABLE public.visits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.visits FROM anon, authenticated;
GRANT SELECT ON TABLE public.visits TO authenticated;

CREATE POLICY visits_select_self
ON public.visits
FOR SELECT
TO authenticated
USING (member_account_id = (SELECT public.current_account_id()));

CREATE POLICY visits_select_owner
ON public.visits
FOR SELECT
TO authenticated
USING ((SELECT public.is_active_owner()));

CREATE FUNCTION public.member_check_in(p_entered_at timestamp with time zone)
RETURNS public.visits
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    account_id bigint := public.current_account_id();
    created_visit public.visits;
    visit_date date := (p_entered_at AT TIME ZONE 'Asia/Singapore')::date;
BEGIN
    IF account_id IS NULL OR NOT EXISTS (
        SELECT 1
        FROM public.accounts
        WHERE id = account_id
          AND role = 'MEMBER'
          AND is_active
    ) THEN
        RAISE EXCEPTION 'An active Member account is required'
            USING ERRCODE = '42501';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.memberships
        WHERE member_account_id = account_id
          AND is_active
          AND start_date <= visit_date
          AND expiry_date >= visit_date
    ) THEN
        RAISE EXCEPTION 'An active Membership is required to check in'
            USING ERRCODE = '23514';
    END IF;

    INSERT INTO public.visits (member_account_id, entered_at)
    VALUES (account_id, p_entered_at)
    RETURNING * INTO created_visit;

    RETURN created_visit;
END;
$$;

CREATE FUNCTION public.member_check_out(p_exited_at timestamp with time zone)
RETURNS public.visits
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    account_id bigint := public.current_account_id();
    closed_visit public.visits;
BEGIN
    IF account_id IS NULL THEN
        RAISE EXCEPTION 'An active Member account is required'
            USING ERRCODE = '42501';
    END IF;

    UPDATE public.visits
    SET exited_at = p_exited_at
    WHERE member_account_id = account_id
      AND exited_at IS NULL
      AND entered_at < p_exited_at
    RETURNING * INTO closed_visit;

    IF closed_visit.id IS NULL THEN
        RAISE EXCEPTION 'No open Visit can be checked out at that time'
            USING ERRCODE = '23514';
    END IF;

    RETURN closed_visit;
END;
$$;

CREATE FUNCTION public.owner_correct_visit(
    p_visit_id bigint,
    p_entered_at timestamp with time zone,
    p_exited_at timestamp with time zone,
    p_reason text
)
RETURNS public.visits
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    owner_id bigint := public.current_account_id();
    corrected_visit public.visits;
BEGIN
    IF NOT public.is_active_owner() THEN
        RAISE EXCEPTION 'An active Owner account is required'
            USING ERRCODE = '42501';
    END IF;
    IF p_exited_at IS NOT NULL AND p_exited_at <= p_entered_at THEN
        RAISE EXCEPTION 'Exit time must be after entry time'
            USING ERRCODE = '23514';
    END IF;
    IF length(trim(coalesce(p_reason, ''))) = 0 THEN
        RAISE EXCEPTION 'Correction reason is required'
            USING ERRCODE = '23514';
    END IF;

    UPDATE public.visits
    SET entered_at = p_entered_at,
        exited_at = p_exited_at,
        corrected_at = now(),
        corrected_by_account_id = owner_id,
        correction_reason = trim(p_reason)
    WHERE id = p_visit_id
    RETURNING * INTO corrected_visit;

    IF corrected_visit.id IS NULL THEN
        RAISE EXCEPTION 'Visit not found' USING ERRCODE = 'P0002';
    END IF;

    RETURN corrected_visit;
END;
$$;

REVOKE ALL ON FUNCTION public.member_check_in(timestamp with time zone)
    FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.member_check_out(timestamp with time zone)
    FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.owner_correct_visit(
    bigint,
    timestamp with time zone,
    timestamp with time zone,
    text
) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.member_check_in(timestamp with time zone)
    TO authenticated;
GRANT EXECUTE ON FUNCTION public.member_check_out(timestamp with time zone)
    TO authenticated;
GRANT EXECUTE ON FUNCTION public.owner_correct_visit(
    bigint,
    timestamp with time zone,
    timestamp with time zone,
    text
) TO authenticated;
