DROP INDEX public.accounts_one_owner;

GRANT SELECT ON TABLE public.accounts TO service_role;

CREATE TABLE public.owner_account_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id bigint NOT NULL REFERENCES public.accounts(id),
    target_account_id bigint NOT NULL REFERENCES public.accounts(id),
    action text NOT NULL CHECK (action IN ('CREATED', 'ACTIVATED', 'DEACTIVATED')),
    occurred_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.owner_account_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.owner_account_audit FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.owner_account_audit TO authenticated;

CREATE POLICY owner_account_audit_select_owner
ON public.owner_account_audit
FOR SELECT
TO authenticated
USING ((SELECT public.is_active_owner()));

CREATE FUNCTION public.protect_final_active_owner()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF OLD.role = 'OWNER'
       AND OLD.is_active
       AND (
           TG_OP = 'DELETE'
           OR NEW.role <> 'OWNER'
           OR NOT NEW.is_active
       ) THEN
        PERFORM pg_catalog.pg_advisory_xact_lock(
            pg_catalog.hashtextextended('gymflow.active_owners', 0)
        );
        IF NOT EXISTS (
            SELECT 1
              FROM public.accounts
             WHERE role = 'OWNER'
               AND is_active
               AND id <> OLD.id
        ) THEN
            RAISE EXCEPTION 'At least one active Owner is required';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER accounts_protect_final_active_owner
BEFORE UPDATE OF role, is_active OR DELETE ON public.accounts
FOR EACH ROW EXECUTE FUNCTION public.protect_final_active_owner();

CREATE FUNCTION public.create_owner_record(
    p_auth_user_id uuid,
    p_actor_account_id bigint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    owner_email text;
    owner_account_id bigint;
BEGIN
    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended('gymflow.active_owners', 0)
    );
    IF NOT EXISTS (
        SELECT 1
          FROM public.accounts
         WHERE id = p_actor_account_id
           AND role = 'OWNER'
           AND is_active
    ) THEN
        RAISE EXCEPTION 'An active Owner account is required' USING ERRCODE = '42501';
    END IF;

    SELECT lower(trim(email))
      INTO owner_email
      FROM auth.users
     WHERE id = p_auth_user_id
       AND email IS NOT NULL;
    IF owner_email IS NULL THEN
        RAISE EXCEPTION 'A matching Auth user with an email address is required';
    END IF;

    INSERT INTO public.accounts (auth_user_id, email, role, is_active)
    VALUES (p_auth_user_id, owner_email, 'OWNER', true)
    RETURNING id INTO owner_account_id;

    INSERT INTO public.owner_account_audit (
        actor_account_id,
        target_account_id,
        action
    ) VALUES (
        p_actor_account_id,
        owner_account_id,
        'CREATED'
    );
    RETURN owner_account_id;
END;
$$;

CREATE FUNCTION public.set_owner_active(
    p_target_account_id bigint,
    p_active boolean,
    p_actor_account_id bigint
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    previous_active boolean;
BEGIN
    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended('gymflow.active_owners', 0)
    );
    IF NOT EXISTS (
        SELECT 1
          FROM public.accounts
         WHERE id = p_actor_account_id
           AND role = 'OWNER'
           AND is_active
    ) THEN
        RAISE EXCEPTION 'An active Owner account is required' USING ERRCODE = '42501';
    END IF;
    IF p_target_account_id = p_actor_account_id THEN
        RAISE EXCEPTION 'Owners cannot change their own active state'
            USING ERRCODE = '22023';
    END IF;

    SELECT is_active
      INTO previous_active
      FROM public.accounts
     WHERE id = p_target_account_id
       AND role = 'OWNER'
     FOR UPDATE;
    IF previous_active IS NULL THEN
        RAISE EXCEPTION 'Owner account not found';
    END IF;
    IF previous_active = p_active THEN
        RETURN false;
    END IF;

    UPDATE public.accounts
       SET is_active = p_active,
           updated_at = now()
     WHERE id = p_target_account_id;

    INSERT INTO public.owner_account_audit (
        actor_account_id,
        target_account_id,
        action
    ) VALUES (
        p_actor_account_id,
        p_target_account_id,
        CASE WHEN p_active THEN 'ACTIVATED' ELSE 'DEACTIVATED' END
    );
    RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.protect_final_active_owner()
FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.create_owner_record(uuid, bigint)
FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_owner_active(bigint, boolean, bigint)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.create_owner_record(uuid, bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_owner_active(bigint, boolean, bigint) TO service_role;
