CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;

CREATE TABLE public.accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email text NOT NULL,
    role text NOT NULL CHECK (role IN ('OWNER', 'MEMBER')),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CHECK (email = lower(trim(email)))
);

CREATE UNIQUE INDEX accounts_email_unique ON public.accounts (lower(email));
CREATE UNIQUE INDEX accounts_one_owner ON public.accounts (role) WHERE role = 'OWNER';

CREATE SEQUENCE public.member_number_sequence START WITH 3;

CREATE TABLE public.member_profiles (
    account_id bigint PRIMARY KEY REFERENCES public.accounts(id) ON DELETE CASCADE,
    member_number text NOT NULL UNIQUE CHECK (member_number ~ '^M[0-9]{4,}$'),
    full_name text NOT NULL CHECK (length(trim(full_name)) > 0),
    phone_number text NOT NULL CHECK (length(trim(phone_number)) > 0),
    date_of_birth date
);

CREATE TABLE public.memberships (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id bigint NOT NULL REFERENCES public.member_profiles(account_id) ON DELETE CASCADE,
    start_date date NOT NULL,
    expiry_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CHECK (expiry_date >= start_date),
    EXCLUDE USING gist (
        member_account_id WITH =,
        daterange(start_date, expiry_date, '[]') WITH &&
    ) WHERE (is_active)
);

CREATE INDEX memberships_member_account_id_idx
    ON public.memberships (member_account_id);

CREATE TABLE public.payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id bigint NOT NULL UNIQUE REFERENCES public.memberships(id) ON DELETE CASCADE,
    amount_cents bigint NOT NULL CHECK (amount_cents > 0),
    method text NOT NULL CHECK (method IN ('CASH', 'CARD', 'TRANSFER')),
    paid_at timestamp with time zone NOT NULL,
    reference text,
    recorded_by_account_id bigint NOT NULL REFERENCES public.accounts(id),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date date NOT NULL,
    amount_cents bigint NOT NULL CHECK (amount_cents > 0),
    method text NOT NULL CHECK (method IN ('CASH', 'CARD', 'TRANSFER')),
    category text NOT NULL CHECK (category IN (
        'MAINTENANCE',
        'UTILITIES',
        'EQUIPMENT',
        'SUPPLIES',
        'RENT',
        'OTHER'
    )),
    description text,
    recorded_by_account_id bigint NOT NULL REFERENCES public.accounts(id),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX expenses_expense_date_idx ON public.expenses (expense_date DESC);

CREATE TABLE public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL CHECK (length(trim(title)) > 0),
    content text NOT NULL CHECK (length(trim(content)) > 0),
    published_at timestamp with time zone NOT NULL,
    created_by_account_id bigint NOT NULL REFERENCES public.accounts(id),
    withdrawn_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CHECK (withdrawn_at IS NULL OR withdrawn_at >= published_at)
);

CREATE INDEX announcements_published_at_idx
    ON public.announcements (published_at DESC);

CREATE TABLE public.workouts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id bigint NOT NULL REFERENCES public.member_profiles(account_id) ON DELETE CASCADE,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    corrected_at timestamp with time zone,
    corrected_by_account_id bigint REFERENCES public.accounts(id),
    correction_reason text,
    CHECK (ended_at IS NULL OR ended_at > started_at),
    CHECK (
        (
            corrected_at IS NULL
            AND corrected_by_account_id IS NULL
            AND correction_reason IS NULL
        )
        OR (
            corrected_at IS NOT NULL
            AND corrected_by_account_id IS NOT NULL
            AND length(trim(correction_reason)) > 0
        )
    )
);

CREATE UNIQUE INDEX workouts_one_open_per_member
    ON public.workouts (member_account_id)
    WHERE ended_at IS NULL;

CREATE INDEX workouts_member_started_at_idx
    ON public.workouts (member_account_id, started_at DESC);

CREATE TABLE public.workout_sets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id bigint NOT NULL REFERENCES public.workouts(id) ON DELETE CASCADE,
    position integer NOT NULL CHECK (position >= 0),
    exercise_name text NOT NULL CHECK (length(trim(exercise_name)) > 0),
    repetitions integer,
    duration_seconds integer,
    resistance_grams bigint CHECK (resistance_grams IS NULL OR resistance_grams >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (workout_id, position),
    CHECK (
        (repetitions IS NOT NULL AND repetitions > 0 AND duration_seconds IS NULL)
        OR (duration_seconds IS NOT NULL AND duration_seconds > 0 AND repetitions IS NULL)
        OR (repetitions IS NULL AND duration_seconds IS NULL)
    )
);

CREATE TABLE public.body_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_account_id bigint NOT NULL REFERENCES public.member_profiles(account_id) ON DELETE CASCADE,
    measurement_date date NOT NULL,
    weight_grams bigint NOT NULL CHECK (weight_grams > 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (member_account_id, measurement_date)
);

CREATE INDEX body_metrics_member_date_idx
    ON public.body_metrics (member_account_id, measurement_date DESC);

CREATE FUNCTION public.add_membership_with_payment(
    p_member_account_id bigint,
    p_start_date date,
    p_expiry_date date,
    p_amount_cents bigint,
    p_method text,
    p_paid_at timestamp with time zone,
    p_reference text,
    p_owner_account_id bigint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    membership_id bigint;
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.accounts
        WHERE id = p_owner_account_id
          AND role = 'OWNER'
          AND is_active
    ) THEN
        RAISE EXCEPTION 'An active Owner account is required'
            USING ERRCODE = '42501';
    END IF;

    INSERT INTO public.memberships (
        member_account_id,
        start_date,
        expiry_date,
        is_active
    )
    VALUES (
        p_member_account_id,
        p_start_date,
        p_expiry_date,
        true
    )
    RETURNING id INTO membership_id;

    INSERT INTO public.payments (
        membership_id,
        amount_cents,
        method,
        paid_at,
        reference,
        recorded_by_account_id
    )
    VALUES (
        membership_id,
        p_amount_cents,
        p_method,
        p_paid_at,
        nullif(trim(p_reference), ''),
        p_owner_account_id
    );

    RETURN membership_id;
END;
$$;

CREATE FUNCTION public.create_member_records(
    p_member_auth_user_id uuid,
    p_email text,
    p_full_name text,
    p_phone_number text,
    p_date_of_birth date,
    p_membership_start date,
    p_membership_expiry date,
    p_payment_amount_cents bigint,
    p_payment_method text,
    p_paid_at timestamp with time zone,
    p_payment_reference text,
    p_owner_account_id bigint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
    member_account_id bigint;
    member_number text;
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.accounts
        WHERE id = p_owner_account_id
          AND role = 'OWNER'
          AND is_active
    ) THEN
        RAISE EXCEPTION 'An active Owner account is required'
            USING ERRCODE = '42501';
    END IF;

    member_number := 'M' || lpad(
        nextval('public.member_number_sequence')::text,
        4,
        '0'
    );

    INSERT INTO public.accounts (auth_user_id, email, role, is_active)
    VALUES (p_member_auth_user_id, lower(trim(p_email)), 'MEMBER', true)
    RETURNING id INTO member_account_id;

    INSERT INTO public.member_profiles (
        account_id,
        member_number,
        full_name,
        phone_number,
        date_of_birth
    )
    VALUES (
        member_account_id,
        member_number,
        trim(p_full_name),
        trim(p_phone_number),
        p_date_of_birth
    );

    PERFORM public.add_membership_with_payment(
        member_account_id,
        p_membership_start,
        p_membership_expiry,
        p_payment_amount_cents,
        p_payment_method,
        p_paid_at,
        p_payment_reference,
        p_owner_account_id
    );

    RETURN member_account_id;
END;
$$;

REVOKE ALL ON FUNCTION public.add_membership_with_payment(
    bigint,
    date,
    date,
    bigint,
    text,
    timestamp with time zone,
    text,
    bigint
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.add_membership_with_payment(
    bigint,
    date,
    date,
    bigint,
    text,
    timestamp with time zone,
    text,
    bigint
) TO service_role;

REVOKE ALL ON FUNCTION public.create_member_records(
    uuid,
    text,
    text,
    text,
    date,
    date,
    date,
    bigint,
    text,
    timestamp with time zone,
    text,
    bigint
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_member_records(
    uuid,
    text,
    text,
    text,
    date,
    date,
    date,
    bigint,
    text,
    timestamp with time zone,
    text,
    bigint
) TO service_role;

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.body_metrics ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.accounts FROM anon, authenticated;
REVOKE ALL ON TABLE public.member_profiles FROM anon, authenticated;
REVOKE ALL ON TABLE public.memberships FROM anon, authenticated;
REVOKE ALL ON TABLE public.payments FROM anon, authenticated;
REVOKE ALL ON TABLE public.expenses FROM anon, authenticated;
REVOKE ALL ON TABLE public.announcements FROM anon, authenticated;
REVOKE ALL ON TABLE public.workouts FROM anon, authenticated;
REVOKE ALL ON TABLE public.workout_sets FROM anon, authenticated;
REVOKE ALL ON TABLE public.body_metrics FROM anon, authenticated;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
